---
title: MattLovesJenni Blog
baseURL: "/"
params:
  layout_style: grid
  palette: blue
  header:
    title: MattLovesJenni
    logo_img: ''
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
